### ISSUE TITLE
OxalisAs4TransmissionException: Could not extract SBDH from payload

### ISSUE THREAD

**Issue by HarshaSuranjith** [difi/Oxalis-AS4#110]
Following exception thrown when trying to transmit large files ( > 15 mb)

```
11:05:55.614 [pool-3-thread-9] ERROR c.c.b.o.s.OxalisOutboundMessageDispatcher - Error occurred while sending message: PRODEFAKTB2B_EHF_IN_FAKTURA_2020-03-04_NO989373560MVA_4006259.xml-125051397.xml
com.compello.b2b.oxalisout.service.InvalidTransmissionException: Failed to transmit file: PRODEFAKTB2B_EHF_IN_FAKTURA_2020-03-04_NO989373560MVA_4006259.xml-125051397.xml after 5 attempts
        at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.transmit(OxalisOutboundMessageDispatcher.java:86)
        at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.dispatch(OxalisOutboundMessageDispatcher.java:57)
        at com.compello.b2b.oxalisout.service.FileProcessor.processFile(FileProcessor.java:39)
        at com.compello.b2b.oxalisout.service.FileProcessor.run(FileProcessor.java:89)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:108)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
        at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.transmit(OxalisOutboundMessageDispatcher.java:79)
        ... 8 common frames omitted
Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Could not extract SBDH from payload
        at no.difi.oxalis.as4.outbound.TransmissionResponseConverter.convert(TransmissionResponseConverter.java:56)
        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:106)
        ... 14 common frames omitted
```

Running : Oxalis-AS4-4.1.8

**Comment by FrodeBjerkholt** [comment]
As the Exception says, the file your are trying to send is missing the required StandardBusinessDocumentHeader.

**Comment by FrodeBjerkholt** [comment]
Can you confirm that this was the problem, please?

**Comment by HarshaSuranjith** [comment]
Hi, apologies for the delay.

Seems to be related with the long transfer durations. I have updated the libs to the latest version and currently failing instances are very few.  

Will investigate further and reopen if issue reappears.

**Comment by FrodeBjerkholt** [comment]
Long transfer duration probably has to do with the receiving side. There could be that the receiving AP hasn't updated their AP to the latest release.
