### ISSUE TITLE
Problem with AS4 and PEPPOL testbed

### ISSUE THREAD

**Issue by evgenywork** [difi/Oxalis-AS4#12]
Hi Oxalis team,

I tried to pass PEPPOL testbed (https://testbed.peppol.eu/secure/suite/view).
AS2 was passed perfectly without any errors, but AS4 on outbound test crashed with security exception.
I tested it with Oxalis version 4.0.2 and 4.0.4.

My **oxalis.config** file:
```
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=TEST.p12
     password = "pass"
     key.alias = "key"
     key.password = "pass"
 }

transport.as4_peppol_v1_to_v2_adapter = {
      profile: bdxr-transport-ebms3-as4-v1p0
      sender: oxalis-as4
      weight: 5000
}

oxalis.truststore {
     password = "pass"
     path=TEST.p12
}

 # The relative name of the directory holding plugin
 #oxalis.path.plugin = oxalis-plugin

 # Signals to Oxalis that we should look for plugin
 #oxalis.persister.receipt = plugin

 # Where to store inbound files
 oxalis.path.inbound = /var/peppol/IN
```

The error that i received:

```
2019-02-28 07:07:36,844  INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat/.oxalis/oxalis-server/target/oxalis-server-4.0.2-full/oxalis-server
2019-02-28 07:07:36,850  INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat/.oxalis/oxalis-server/target/oxalis-server-4.0.2-full/oxalis-server/conf
2019-02-28 07:07:36,850  INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat/.oxalis/oxalis-server/target/oxalis-server-4.0.2-full/oxalis-server/conf/oxalis.conf
2019-02-28 07:07:36,854  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: HTTP
2019-02-28 07:07:36,860  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_TOTAL: 20
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_MAX_ROUTE: 2
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_CONNECT: 0
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_READ: 0
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Error
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TRACKER: quiet
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: AS2
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HOSTNAME:
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => NOTIFICATION: not.in.use@difi.no
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => MSGID_GENERATOR: default
2019-02-28 07:07:36,861  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: File system
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => CONF: conf
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => INBOUND: /var/peppol/IN
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PLUGIN: plugin
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Key store
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PATH: TEST.p12
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PASSWORD: pass
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_ALIAS: key
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_PASSWORD: pass
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Header
2019-02-28 07:07:36,862  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PARSER: sbdh
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Persister
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PAYLOAD: default
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => RECEIPT: default
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HANDLER: default
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Tracing
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => REPORTER: noop
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HTTP: null
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Tag
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => GENERATOR: noop
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Timestamp
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: system
2019-02-28 07:07:36,863  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Evidence
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: rem
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Trust store
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PATH: TEST.p12
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PASSWORD: pass
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Transformer
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => DETECTOR: legacy
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => WRAPPER: xml
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Statistics
2019-02-28 07:07:36,864  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: noop
2019-02-28 07:07:36,865  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Transmission
2019-02-28 07:07:36,865  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => VERIFIER: default
2019-02-28 07:07:36,865  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: AS4
2019-02-28 07:07:36,865  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HOSTNAME:
2019-02-28 07:07:36,865  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => MSGID_GENERATOR: default
2019-02-28 07:07:36,865  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Logging
2019-02-28 07:07:36,866  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => CONFIG: null
2019-02-28 07:07:36,866  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: logback
2019-02-28 07:07:39,610  INFO [no.difi.oxalis.commons.mode.ModeModule] Detected mode: TEST
2019-02-28 07:07:39,668  INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Inbound folder: /var/peppol/IN
2019-02-28 07:07:40,501  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
2019-02-28 07:07:40,502  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => bdxr-transport-ebms3-as4-v1p0
2019-02-28 07:07:40,502  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
2019-02-28 07:07:40,502  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0
2019-02-28 07:07:40,502  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0
2019-02-28 07:08:34,335  WARN [org.apache.cxf.phase.PhaseInterceptorChain] Interceptor for {http://inbound.as4.oxalis.difi.no/}As4ProviderService has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: A security error was encountered when verifying the message
        at org.apache.cxf.ws.security.wss4j.WSS4JUtils.createSoapFault(WSS4JUtils.java:236)
        at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:341)
        at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:176)
        at no.difi.oxalis.as4.inbound.OxalisAS4WsInInterceptor.handleMessage(OxalisAS4WsInInterceptor.java:39)
        at no.difi.oxalis.as4.inbound.OxalisAS4WsInInterceptor.handleMessage(OxalisAS4WsInInterceptor.java:20)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:191)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: Error during certificate path validation: No trusted certs found
        at org.apache.wss4j.common.crypto.Merlin.verifyTrust(Merlin.java:797)
        at org.apache.wss4j.common.crypto.Merlin.verifyTrust(Merlin.java:887)
        at org.apache.wss4j.dom.validate.SignatureTrustValidator.verifyTrustInCerts(SignatureTrustValidator.java:109)
        at org.apache.wss4j.dom.validate.SignatureTrustValidator.validate(SignatureTrustValidator.java:64)
        at org.apache.wss4j.dom.processor.SignatureProcessor.handleToken(SignatureProcessor.java:192)
        at org.apache.wss4j.dom.engine.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:340)
        at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:285)
        ... 40 common frames omitted
```

The error on peppol testbed:

![error_peppol](https://user-images.githubusercontent.com/13591373/53552488-76e84e80-3b4c-11e9-9203-d0176073d1c6.png)

What i do wrong? Can you please help me?

Best Regards
Evgeny Shevchenko

**Comment by artjomsk** [comment]
Most likely you don't have trust certificate in truststore.
As I see you have one store for both oxalis.keystore and  oxalis.truststore(this one is used only by AS4).
Check if you have certificate PEPPOL Root TEST CA - G2 in the store.

**Comment by evgenywork** [comment]
Thank you very much!
I noticed that my p12 store has a different certificate alias (PEPPOL ACCESS POINT TEST CA - G2) than you wrote.
I downloaded this certificate and everything works fine.

**Comment by alessandrolorenzetti** [comment]
Hi evgenywork, 

I have to do PEPPOL testbed (https://testbed.peppol.eu/secure/suite/view) for my Access Point (Oxalis AS4)

I was able to get a document from the PEPPOL server Testbed (Oxalis AS4 Server Tomcat is OK) but when I try to send the document back (through oxalis-standalone) to PEPPOL testbed I get an error "A security error was encountered when verifying the message" (see https://github.com/difi/Oxalis-AS4/issues/15)

Do you have any tips for my problem?

Best Regards
Alessandro Lorenzetti

**Comment by ekorra** [comment]
As the original problem is solved we will close this issue. 
Kudos to @artjomsk
