### ISSUE TITLE
Default key managers cannot be initialized: Password must not be null

### ISSUE THREAD

**Issue by sanderverhoeven** [difi/Oxalis-AS4#121]
Sending a message is not working anymore, It can not find  my keystore so it seems.

Error message:

```
2020-05-19 14:30:16,622 WARN [org.apache.cxf.transport.https.SSLUtils] Default key managers cannot be initialized: Password must not be null
java.security.UnrecoverableKeyException: Password must not be null
        at sun.security.provider.JavaKeyStore.engineGetKey(Unknown Source)
        at sun.security.provider.JavaKeyStore$JKS.engineGetKey(Unknown Source)
        at sun.security.provider.KeyStoreDelegator.engineGetKey(Unknown Source)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(Unknown Source)
        at java.security.KeyStore.getKey(Unknown Source)
        at sun.security.ssl.SunX509KeyManagerImpl.<init>(Unknown Source)
        at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(Unknown Source)
        at javax.net.ssl.KeyManagerFactory.init(Unknown Source)
        at org.apache.cxf.configuration.jsse.SSLUtils.loadDefaultKeyManagers(SSLUtils.java:116)
        at org.apache.cxf.configuration.jsse.SSLUtils.getDefaultKeyStoreManagers(SSLUtils.java:89)
        at org.apache.cxf.transport.https.SSLUtils.getSSLContext(SSLUtils.java:75)
        at org.apache.cxf.transport.https.HttpsURLConnectionFactory.decorateWithTLS(HttpsURLConnectionFactory.java:144)
        at org.apache.cxf.transport.https.HttpsURLConnectionFactory.createConnection(HttpsURLConnectionFactory.java:101)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:121)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:125)
        at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:505)
        at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2020-05-19 14:30:17,503 WARN [org.apache.wss4j.common.crypto.CryptoBase] No Subject DN Certificate Constraints were defined. This could be a security issue
8b61c20c-c6fd-44a9-bad9-c109cd0d24ff@host.docker.internal transmission took 1663 ms
Average transmission time was 1663.0ms
Total time spent: 2s
Attempted to send 1 files
Failed transmissions: 0
Transmission speed 0 documents per second

```

This is my oxalis config:

```
oxalis.keystore.path = cert.p12
oxalis.keystore.password = password
oxalis.keystore.key.alias = Alias
oxalis.keystore.key.password = password
 
oxalis.truststore.path = complete-truststore.jks
oxalis.truststore.password = peppol

#security.truststore.ap= complete-truststore.jks
#security.truststore.password=peppol

defaults.transport.as4_peppol_v2 = {
    profile: peppol-transport-as4-v2_0
    sender: oxalis-as4
    weight: 9001
}

transport.as4_peppol_v1_to_v2_adapter = {
      profile: bdxr-transport-ebms3-as4-v1p0
      sender: oxalis-as4
      weight: 5000
}

oxalis.path.inbound = peppol/IN
 
#oxalis.logging.config=logback.xml 
```
Logback logging:

[oxalis.log](https://github.com/difi/Oxalis-AS4/files/4650474/oxalis.log)

**Comment by FrodeBjerkholt** [comment]
Is this in production or are you trying to perfom the connectivity test or sending to the testbed? It should be unnecessary to specify a truststore if you are sending with the TEST or PRODUCTION mode, since the Peppol certificates are accepted using the truststore that are included in the JDK.

The correct properties to specify a different truststore are the ones you have comment out. (security.truststore.ap)

**Comment by sanderverhoeven** [comment]
This is to send over the test network, but even without the truststore this is nog working.

still receiving error:

```
2020-05-19 15:32:50,244 WARN [org.apache.cxf.transport.https.SSLUtils] Default key managers cannot be initialized: Password must not be null
java.security.UnrecoverableKeyException: Password must not be null
        at sun.security.provider.JavaKeyStore.engineGetKey(Unknown Source)
        at sun.security.provider.JavaKeyStore$JKS.engineGetKey(Unknown Source)
        at sun.security.provider.KeyStoreDelegator.engineGetKey(Unknown Source)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(Unknown Source)
        at java.security.KeyStore.getKey(Unknown Source)
        at sun.security.ssl.SunX509KeyManagerImpl.<init>(Unknown Source)
        at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(Unknown Source)
        at javax.net.ssl.KeyManagerFactory.init(Unknown Source)
        at org.apache.cxf.configuration.jsse.SSLUtils.loadDefaultKeyManagers(SSLUtils.java:116)
        at org.apache.cxf.configuration.jsse.SSLUtils.getDefaultKeyStoreManagers(SSLUtils.java:89)
        at org.apache.cxf.transport.https.SSLUtils.getSSLContext(SSLUtils.java:75)
        at org.apache.cxf.transport.https.HttpsURLConnectionFactory.decorateWithTLS(HttpsURLConnectionFactory.java:144)
        at org.apache.cxf.transport.https.HttpsURLConnectionFactory.createConnection(HttpsURLConnectionFactory.java:101)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:121)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:125)
        at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:505)
        at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2020-05-19 15:32:51,181 WARN [org.apache.wss4j.common.crypto.CryptoBase] No Subject DN Certificate Constraints were defined. This could be a security issue
```
It has worked before. running the command as a local admin. any Ideas. running the latest versions of Standalone.jar and as4 files 4.1.9

**Comment by FrodeBjerkholt** [comment]
I haven't seen this before. The error message indicates that this has something to do with the default keystore. I think it means that CXF is trying to load the keystore referenced by the "javax.net.ssl.keyStore" system property?

**Comment by sanderverhoeven** [comment]
My Java version was corrupted. the issue is fixed by using a newer version of JAVA
