### ISSUE TITLE
Pmode configuration 

### ISSUE THREAD

**Issue by evgenywork** [difi/Oxalis-AS4#17]
Hello Oxalis team,
I tried to pass CEF eDelivery Connectivity test with static scenario.
CEF eDelivery support sent me pmode file, keystore and truststore.
Keystore and truststore i specified in my oxalis.conf file, but i don't know how to implement pmode file.
Can you give me instructions how to configure pmode please?

My **oxalis.conf**:

```
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=ceftestpartyXXgwkeystore.jks
     password = "pass"
     key.alias = "ceftestpartyXXgw"
     key.password = "pass"
 }

transport.as4_peppol_v1_to_v2_adapter = {
      profile: bdxr-transport-ebms3-as4-v1p0
      sender: oxalis-as4
      weight: 5000
}

oxalis.truststore {
     password = "pass"
     path=ceftestpartyXXgwtruststore.jks

}

oxalis.path.inbound = /var/peppol/IN
```

Best Regards
Evgeny Shevchenko

**Comment by ekorra** [comment]
Oxalis does not have a consept of pModes. It currently hardcoded to work with the OpenPEPPOL pModes. 
You can configure Oxalis for the test by changing the following properties in the file[ Constants.java](https://github.com/difi/Oxalis-AS4/blob/master/src/main/java/no/difi/oxalis/as4/util/Constants.java), and recompile. 
* PARTY_ID_TYPE
* SERVICE_TYPE
* AGREEMENT_REF 

In future version of the AS4 plugging we will make it easier to perform this test

**Comment by evgenywork** [comment]
Hello Espen

Thank you for your reply!
I changed these constants and recompiled my project.


I tried to send CEF test message  
_message example:_
```
<?xml version="1.0" encoding="UTF-8"?>
<Request>
  eDelivery AS4 Connectivity test. Sending Message
</Request>
```
and i had next error:
```
2019-05-16 11:45:38,694 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1
```

My oxalis.conf file:
```
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=ceftestparty64gwkeystore.jks
     password = "123"
     key.alias = "ceftestparty64gw"
     key.password = "123"
 }

transport.as4_peppol_v1_to_v2_adapter = {
      profile: bdxr-transport-ebms3-as4-v1p0
      sender: oxalis-as4
      weight: 5000
}

oxalis.truststore {
     password = "123"
     path=ceftestparty64gwtruststore.jks

}

mode.conformance=test
mode.conformance.lookup.locator.hostname="acc.edelivery.tech.ec.europa.eu/edelivery-sml/"
mode.conformance.security.validator.class="no.difi.vefa.peppol.security.util.EmptyCertificateValidator"

security.validator.class="no.difi.vefa.peppol.security.util.EmptyCertificateValidator"

# Where to store inbound files
oxalis.path.inbound = /var/peppol/IN
```

Command:
```
java -cp /opt/tomcat/.oxalis/oxalis-dist/oxalis-standalone-as4/standalone/*:/opt/tomcat/.oxalis/oxalis-dist/oxalis-standalone-as4/as4/*  eu.sendregning.oxalis.Main 
-f test_static_as4_cef.xml 
-u http://40.115.23.114:8080/domibus/services/msh?domain=static 
-s ceftestparty64gw 
-r cefsupportgw 
--protocol peppol-transport-as4-v2_0 
-cert ../ceftestparty64gw.crt
```
Is this a same problem https://github.com/difi/oxalis/issues/412 ?
Did you resolve it?

Best Regards
Evgeny Shevchenko

**Comment by ekorra** [comment]
The new AS4 plugin, [RC7](https://github.com/difi/Oxalis-AS4/releases/tag/4.1.0-RC7), contains solutions to this and other issues regarding CEF connectivity-test. 
Detailed description of configutation chanes regarding the CEF conectivitytest could be found [here](https://github.com/difi/Oxalis-AS4/blob/master/docs/CEF-connectivity.md).
