### ISSUE TITLE
AS4 module not detected and file transfer fails

### ISSUE THREAD

**Issue by HarshaSuranjith** [difi/Oxalis-AS4#25]
I have deployed an Oxalis instance with AS4 module. 
```
OS : Ubuntu 18.04
JDK : openjdk version "1.8.0_222"
Oxalis : v4.0.4
Oxalis-AS4: Oxalis-AS4 RC8
```
when calling `http://localhost:8080/oxalis/as4` proper response is received (Hello AS4 World).

But when I try to send a file to AS4 endpoint using `oxalis-standalone.jar` with oxalis-as4 jar files included in the classpath, following error is produced by oxalis-standalone. 
It also shows that only `AS2` transport profiles are deployed.

### oxalis-standalone.log
[oxalis-standalone.log](https://github.com/difi/Oxalis-AS4/files/3620666/oxalis-standalone.log)

```
2019-09-17 15:01:13,028 WARN [no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour. 
2019-09-17 15:01:14,107 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No Content-Type header in response, probably a server error. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No Content-Type header in response, probably a server error.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No Content-Type header in response, probably a server error.
	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:287)
	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:247)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:156)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Total time spent: 1s
Attempted to send 0 files
Failed transmissions: 1

```
Server throws following exception.
### catalina.out
[catalina.out.log](https://github.com/difi/Oxalis-AS4/files/3620657/catalina.out.log)

```
14:28:30.084 [http-nio-8080-exec-8] WARN  o.a.cxf.phase.PhaseInterceptorChain - Interceptor for has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Error reading XMLStreamReader: Unexpected character '-' (code 45) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at org.apache.cxf.binding.soap.interceptor.ReadHeadersInterceptor.handleMessage(ReadHeadersInterceptor.java:292)
	at org.apache.cxf.binding.soap.interceptor.ReadHeadersInterceptor.handleMessage(ReadHeadersInterceptor.java:70)
```

I have deployed this on two computers, and produces the same result.

What can be causing this issue ? Thanks in advance for your support !!

Regards,
Harsha

**Comment by yak1975** [comment]
Hi,

I have the same issue. How did you fix it?

Thank you

Gianluca

**Comment by TTD93** [comment]
I've the same problem, I don't see the answer here. Why was the thread closed?

**Comment by HarshaSuranjith** [comment]
> Hi,
> 
> I have the same issue. How did you fix it?
> 
> Thank you
> 
> Gianluca

are you running on OpenJDK ??

**Comment by HegeErdal** [comment]
If anyone come across this issue: What fixed it for me was to attach the following argument: 
--protocol peppol-transport-as4-v2_0

That is: 
java -DOXALIS_HOME=path-to-oxalis-home -classpath "standalone/*:as4/*" eu.sendregning.oxalis.Main  -f Oxalis-AS4/src/test/resources/simple-sbd.xml -u http://localhost:8080/as4 --cert conf/outcert.crt --protocol peppol-transport-as4-v2_0

**Comment by nkoudelia** [comment]
Thank you @HegeErdal, you just saved my day :heart:
