### ISSUE TITLE
issue starting with as4

### ISSUE THREAD

**Issue by Brummos** [difi/Oxalis-AS4#34]
Hello team,

We just started setting up as4 and we run into the following error when starting oxalis with as4. Starting with as2 works fine.

We are using as4 rc10 and oxalis 4.1.0

> 06-Nov-2019 06:56:24.678 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [no.difi.oxalis.dist.war.WarGuiceFilter]
 java.lang.IllegalArgumentException: Cannot create URL for this address /
	at com.sun.xml.ws.transport.http.server.EndpointImpl.publish(EndpointImpl.java:238)
	at com.sun.xml.ws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:154)
	at javax.xml.ws.Endpoint.publish(Endpoint.java:272)
	at no.difi.oxalis.as4.inbound.As4EndpointsPublisherImpl.publish(As4EndpointsPublisherImpl.java:49)
	at no.difi.oxalis.as4.inbound.As4Servlet.loadBus(As4Servlet.java:59)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.init(CXFNonSpringServlet.java:83)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:119)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:80)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:102)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:232)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4491)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1840)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:525)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:424)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:969)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:261)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)

Any help would be appreciated

**Comment by fmendicino** [comment]
I have the same Exception, what could be the problem?

**Comment by fmendicino** [comment]
> I have the same Exception, what could be the problem?

I solved: in my case, as could be deduced from the stacktrace, the container did not associate cxf as the implementation of Endpoint:

java.lang.IllegalArgumentException: Cannot create URL for this address /
        at **com.sun.xml.ws.transport.http.server.EndpointImpl**.publish(EndpointImpl.java:237)
        at **com.sun.xml.ws.spi.ProviderImpl**.createAndPublishEndpoint(ProviderImpl.java:149)
        at javax.xml.ws.Endpoint.publish(Endpoint.java:287)
        at no.difi.oxalis.as4.inbound.As4EndpointsPublisherImpl.publish(As4EndpointsPublisherImpl.java:49)
...

The solution was to put in the folder _src/main/resources/META-INF/services_ the file named javax.xml.ws.spi.Provider with inside: org.apache.cxf.jaxws.spi.ProviderImpl

**Comment by RvanMaarenApro** [comment]
> The solution was to put in the folder _src/main/resources/META-INF/services_ the file named javax.xml.ws.spi.Provider with inside: org.apache.cxf.jaxws.spi.ProviderImpl

Could you please give me some more background on this resolution ? I do not seem to find metioned files.

Regards,

**Comment by fmendicino** [comment]
> > The solution was to put in the folder _src/main/resources/META-INF/services_ the file named javax.xml.ws.spi.Provider with inside: org.apache.cxf.jaxws.spi.ProviderImpl
> 
> Could you please give me some more background on this resolution ? I do not seem to find metioned files.
> 
> Regards,

Let me explain better, in the _src/ main/ resources/META-INF/services_ folder of your module, you should create a file with the name _javax.xml.ws.spi.Provider_ and text: org.apache.cxf.jaxws.spi.ProviderImpl
The above configuration will specify to use the lib cxf as implementation of the WS Endpoint
