### ISSUE TITLE
AS4 WebServiceTransport Exception

### ISSUE THREAD

**Issue by ig2503** [difi/Oxalis-AS4#4]
Hi Oxalis team,
we implemented AS as described here:
https://github.com/difi/Oxalis-AS4/releases

While running standalone AS4: java -classpath standalone/target/*:as4/* eu.sendregning.oxalis.Main -f standalone/src/test/resources/BII04_T10_PEPPOL-v2.0_invoice_DE.xml -r 9930:DE210157578  -s 9930:DE210157578 
we are running into this exception:
2019-01-23 10:31:47,753 INFO [org.springframework.oxm.jaxb.Jaxb2Marshaller] Creating JAXBContext with context path [no.difi.commons.sbdh.jaxb:org.xmlsoap.schemas.soap.envelope:org.w3.soap:org.w3.xmldsig:org.oasis_open.docs.ebxml_bp.ebbp_signals_2:org.oasis_open.docs.ebxml_msg.ebms.v3_0.ns.core._200704]
2019-01-23 10:31:53,483 ERROR [no.difi.oxalis.commons.error.QuietErrorTracker] [3fc18115-40a5-4efc-87c8-ba55da709d11] Not Found [404]
org.springframework.ws.client.WebServiceTransportException: Not Found [404]
        at org.springframework.ws.client.core.WebServiceTemplate.handleError(WebServiceTemplate.java:699)
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:609)
        at no.difi.oxalis.as4.outbound.As4WebServiceTemplate.doSendAndReceive(As4WebServiceTemplate.java:21)
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:57)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFascade.send(As4MessageSenderFascade.java:21)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-01-23 10:31:53,484 ERROR [eu.sendregning.oxalis.Main] Execution failed: org.springframework.ws.client.WebServiceTransportException: Not Found [404]
java.util.concurrent.ExecutionException: org.springframework.ws.client.WebServiceTransportException: Not Found [404]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: org.springframework.ws.client.WebServiceTransportException: Not Found [404]
        at org.springframework.ws.client.core.WebServiceTemplate.handleError(WebServiceTemplate.java:699)
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:609)
        at no.difi.oxalis.as4.outbound.As4WebServiceTemplate.doSendAndReceive(As4WebServiceTemplate.java:21)
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:57)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFascade.send(As4MessageSenderFascade.java:21)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Could you please help us with this issue? What is wrong? Is something missing?
Thank you in advance and best regards,
IG

**Comment by evenos** [comment]
Hi

From what I can read out of your exemption it seems you are getting a HTTP 404 Not Found response when you are trying to send the message. Is the remote AP endpoint reachable from the application?

**Comment by ekorra** [comment]
As there is no replay to this question we will close this issue
