### ISSUE TITLE
AS4 Message delivery failure: signature or decryption was invalid

### ISSUE THREAD

**Issue by amaters-easy** [difi/Oxalis-AS4#43]
We are running Oxalis 4.0.4 with AS4 software using difi/oxalis-as4:4.1.0-RC10 docker image. During the proces of sending a document an exception is thrown: 

```
ERROR [no.difi.oxalis.commons.error.QuietErrorTracker] [] [d38b2d32-77a1-4d10-8176-24aff0c97d08] The signature or decryption was invalid 
javax.xml.ws.soap.SOAPFaultException: The signature or decryption was invalid
	at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
	at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:144)
	at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:21)
	at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

When sending from server A to server B everything works. Sending from server A to C the above error is thrown.

What to do to figure out what causes this behaviour? I am by no means an expert on this subject.

**Comment by kukel** [comment]
Multiple options
1.  Run the application with debug logging and see if you get more info
2. Try running the application in an IDE and run in debug mode and step trough it
3. Try to 'dump' the full content your receive on the server (as early as possible) and use that in a unit test to try to reproduce the issue.
4: Hire someone to help with this.

**Comment by amaters-easy** [comment]
Issue can be closed. cause was the receiving end was running an old (bugged) version of oxalis AS4
