### ISSUE TITLE
"No Content-Type header in response, probably a server error."

### ISSUE THREAD

**Issue by Grasrota** [difi/Oxalis-AS4#45]
Java version: **1.8.0_231**
Oxalis: **v4.1.0**
Oxalis-AS4: **Oxalis-AS4 RC10**

I've followed the setup to the letter, and AS4 inbound is configured correctly (http://localhost:8080/oxalis/as4 = Hello AS4 world), however; when I try to send a file to the AS4 endpoint using oxalis-standalone with the AS4-extensions included in the classpath, I'm getting the following error:

`2019-12-09` 09:54:35,508 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles: 
2019-12-09 09:54:35,508 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0 
2019-12-09 09:54:35,508 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2019-12-09 09:54:35,508 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0 
2019-12-09 09:54:35,508 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 

2019-12-09 09:54:35,836 WARN [no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour. 
2019-12-09 09:54:36,383 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No Content-Type header in response, probably a server error. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No Content-Type header in response, probably a server error.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No Content-Type header in response, probably a server error.
	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:287)
	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:247)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:156)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1`

**Command:**
`java -classpath "standalone/*;as4/*" eu.sendregning.oxalis.Main -f EHFInvoice20WithoutSBDH.xml -u http://localhost:8080/oxalis/as4`

The same command with -u http://localhost:8080/oxalis/as2 works without any issues.

What can be causing this issue?

Thanks in advance.

[Tomcat.log](https://github.com/difi/Oxalis-AS4/files/3938739/Tomcat.log)

**Comment by PeterOlausson65** [comment]
I think you must specify the --protocol option (default  busdox-transport-as2-ver1p0)

--protocol  peppol-transport-as4-v2_0

**Comment by Grasrota** [comment]
Thanks PeterOlausson65! That did the trick. :)
