### ISSUE TITLE
Regression? Sending from Oxalis 4.1.0 to 4.0.2 using AS2 is not working

### ISSUE THREAD

**Issue by rdehuyss** [difi/Oxalis-AS4#48]
Hi,

we're currently doing our internal end-to-end tests for the Oxalis AS2 to AS4 upgrade.

During testing, we found out that sending from Oxalis 4.1.0 to an a receiver which runs Oxalis 4.0.4 is not working anymore.

**How to reproduce:**
- Receiver using Oxalis 4.0.2 and peppol-icd version 1.1.1
- Sender using Oxalis 4.1.0 and peppol-icd version 1.1.3
- Send a valid BIS 3 invoice

The logs are attached:
```
no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=400, contents received (4680 characters): ------=_Part_1270_1145533331.1576764436907
Content-Type: multipart/report; Report-Type=disposition-notification; 
	boundary="----=_Part_1268_1582283764.1576764436906"

------=_Part_1268_1582283764.1576764436906
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

= Received headers

date: Thu, 19 Dec 2019 15:07:16 +0100
message-id: <1576764436586.1.322016261.Oxalis@rdehuyss-laptop>
subject: AS2 message from Oxalis
mime-version: 1.0
content-type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1; boundary="----=_Part_1_1492280460.1576764436628"
host: oxalis
connection: close
as2-from: PBE000067
as2-to: PBE000067
disposition-notification-to: not.in.use@difi.no
disposition-notification-options: signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
as2-version: 1.0
user-agent: Oxalis 4.1.0
accept-encoding: gzip,deflate
content-length: 16897

= Error [untracked:9bf972bf-746a-4e29-89ef-da7c56c29cd0]

Invalid message digest.


------=_Part_1268_1582283764.1576764436906
Content-Type: message/disposition-notification
Content-Transfer-Encoding: 7bit

Reporting-UA: Oxalis 4.0.2
Original-Recipient: rfc822; PBE000067
Final-Recipient: rfc822; PBE000067
Original-Message-ID: <1576764436586.1.322016261.Oxalis@rdehuyss-laptop>
Disposition: automatic-action/MDN-sent-automatically; failed/error: integrity-check-failed

------=_Part_1268_1582283764.1576764436906--

------=_Part_1270_1145533331.1576764436907
Content-Type: application/pkcs7-signature; name=smime.p7s; smime-type=signed-data
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"
Content-Description: S/MIME Cryptographic Signature

MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAQAAoIAwggXCMIID
qqADAgECAhBuAwHQj+1nyNwn3Qmly90PMA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNVBAYTAkJFMRkw
FwYDVQQKExBPcGVuUEVQUE9MIEFJU0JMMRYwFAYDVQQLEw1GT1IgVEVTVCBPTkxZMSkwJwYDVQQD
EyBQRVBQT0wgQUNDRVNTIFBPSU5UIFRFU1QgQ0EgLSBHMjAeFw0xODA4MjIwMDAwMDBaFw0yMDA4
MTEyMzU5NTlaME8xEjAQBgNVBAMMCVBCRTAwMDA2NzEXMBUGA1UECwwOUEVQUE9MIFRFU1QgQVAx
EzARBgNVBAoMCkNvZGFib3ggTlYxCzAJBgNVBAYTAkJFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAz2fr4lAio+LJciQmnpb8rP1eIqwabto3DG3/9ybBdsrgbs88/MslVdx/jTBDvEQy
EC6PTkuL/pl+1ngZjCKoYNTO2zIELlzb0Oc2x8vW+2m5/6JYMXsHepe+Sfj0dLlDL40mGBUkhLwM
Ok5SpvTqBYxRrRovS4HH0gOkRfiAW4198GjrQkJY3s3ul+Bhqe/byqbcVx2J9FnvJAxx6v1VYY/c
puakYSPRDt43LflOl+1juZ4C0oC6AGPk5FzTuChpHlDdQkUDJ/OT4mvWUAhLxC5l6Z2Y/JHkSTFe
LzS1wtHyHHj8+g/29Pca2oeRmdERJDp9uzaNJhgszOh9W42ShQIDAQABo4IBfDCCAXgwDAYDVR0T
AQH/BAIwADAOBgNVHQ8BAf8EBAMCA6gwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwHQYDVR0OBBYE
FDMkdv4MdTseT8sBpe7awWSDQGhVMF0GA1UdHwRWMFQwUqBQoE6GTGh0dHA6Ly9wa2ktY3JsLnN5
bWF1dGguY29tL2NhXzZhOTM3NzM0YTM5M2EwODA1YmYzM2NkYThiMzMxMDkzL0xhdGVzdENSTC5j
cmwwNwYIKwYBBQUHAQEEKzApMCcGCCsGAQUFBzABhhtodHRwOi8vcGtpLW9jc3Auc3ltYXV0aC5j
b20wHwYDVR0jBBgwFoAUa29LtvE3uis8fxjNuiuyuXwqN+swLQYKYIZIAYb4RQEQAwQfMB0GE2CG
SAGG+EUBEAECAwEBgamQ4QMWBjk1NzYwODA5BgpghkgBhvhFARAFBCswKQIBABYkYUhSMGNITTZM
eTl3YTJrdGNtRXVjM2x0WVhWMGFDNWpiMjA9MA0GCSqGSIb3DQEBCwUAA4ICAQAvGqx9/Unj9lcG
z/H9F0rhGq7jwnL2nwf/x55B+LQmcBuka7iiVFeB7WUz2xwZ6q6NC6i34hvPJ43aiAa4kNiI2Wau
pMJwVQVFqrNkC4xiOOwwo9oUeQezScCbrebDnqriDYTT5gLOmGWWB5JbXfQUUr7wSWRI4jLWaxnr
xhPEaj2jw4hXedyyaWUflTOF4oKLx5qsX2S1p3dcvmg/VYRnetyeAOq/9aZiUS6hpi7Ur8k6yZeT
3Y/DnaTCxy7ElW2/LHCZSwyfiVsKjoB2HDgCtcbKlE+LSugEjJTG1YGzfStFQyOsWPj1WyyssKUE
E1i55Q5QMMZCAj0L4I1v3bxwdmzcv4+p1gbbvgQ6DpytaQnOvCJBKtKIDJoHaSFShbfmQ1XAeIbM
5ZVhmD3TyJuLVXih8+/hTyViQx33EqeB3A3OwZINqLy0foP5Rt6lKpS6sJ/ZHauy7YIXZ5FNjz3R
WKabGRAPKS2BPPp46aXOQLVeHEWLC20+Jrw7buIqsPpkT+z8+LrbeqVeWyPLSMg7XIQyed2LnMVd
xnjjI9rIJ//xg+e0kqZFakAR4IkYD0i3Mt87XLZ2H/TcI9521HBSdS0no1g8hwuDaNkP9Sz8CZ0N
Lo5vW7aIfS4e+O8xU2SEKMVDTBJM3kQCoVOgpXe7/+oy8Wkdp6xyYS09JCb/AgAAMYICMTCCAi0C
AQEwfzBrMQswCQYDVQQGEwJCRTEZMBcGA1UEChMQT3BlblBFUFBPTCBBSVNCTDEWMBQGA1UECxMN
Rk9SIFRFU1QgT05MWTEpMCcGA1UEAxMgUEVQUE9MIEFDQ0VTUyBQT0lOVCBURVNUIENBIC0gRzIC
EG4DAdCP7WfI3CfdCaXL3Q8wCQYFKw4DAhoFAKCBiDAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcB
MBwGCSqGSIb3DQEJBTEPFw0xOTEyMTkxNDA3MTZaMCMGCSqGSIb3DQEJBDEWBBQTG5hBczbe2Irt
nVNCJmeHaQWRXDApBgkqhkiG9w0BCTQxHDAaMAkGBSsOAwIaBQChDQYJKoZIhvcNAQEBBQAwDQYJ
KoZIhvcNAQEBBQAEggEAhVDTZqnLhnoSAzpDJZsSfM+woz9J73XwdGCrgDITlczx2wTntTb59M1K
kDEbNkQDiVKAIromi2o6N7fIoDBHUx67UUACgRDBG+/ZmFRDjfW+Jid4Y7vi7iatk+PSrc8o5nnn
lzTuLVndOM0yQ6y/MLTHrWTZTL8BxjX1HevTd4cjdc2U9oX540Y2Nzqgh5CJprR5aT+HlYrseEy+
7EmLrf4fz/ne0cd0N2qUOSlqaY4YYWqt5fNgLWQ5sLZhod243tDNdHp2w3IkpPPSowWcP4GlM7/L
DcvKSIuYvK7d/rdlncpJawwJMUZcVbPL/t4LQ2C6pXXoqx5v/+mP2VvLgAAAAAAAAA==
------=_Part_1270_1145533331.1576764436907--

	at no.difi.oxalis.as2.outbound.As2MessageSender.handleFailedRequest(As2MessageSender.java:351)
	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:278)
	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:247)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:156)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
	at com.codabox.einvoicing.connector.peppol.application.service.SendToPeppolService.sendUblDocument(SendToPeppolService.java:112)
	at com.codabox.einvoicing.connector.peppol.application.service.SendToPeppolService.sendDocument(SendToPeppolService.java:80)
	at com.codabox.einvoicing.connector.peppol.api.processor.SendDocumentToPeppolProcessor.process(SendDocumentToPeppolProcessor.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:169)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205)
	at org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.consumeMessage(PubSubInboundChannelAdapter.java:148)
	at org.springframework.cloud.gcp.pubsub.core.subscriber.PubSubSubscriberTemplate.lambda$subscribeAndConvert$1(PubSubSubscriberTemplate.java:152)
	at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:368)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

We found out that problem is caused by:
```
        <dependency>
            <groupId>no.difi.vefa</groupId>
            <artifactId>peppol-icd</artifactId>
            <version>${vefa.peppol.version}</version>
        </dependency>
```
- when using Oxalis 4.1 and peppol-icd version 1.1.1 we can send to Oxalis 4.0.2
- when using Oxalis 4.1 and peppol-icd version 1.1.3 we can NOT send to Oxalis 4.0.2

**Comment by rdehuyss** [comment]
Duplicate of https://github.com/difi/oxalis/issues/424
