### ISSUE TITLE
Prioritized list of transport profiles:

### ISSUE THREAD

**Issue by skizub** [difi/Oxalis-AS4#49]
After successful installation of Oxalis 4.1.0 I'm getting both Hello World pages (for as2 and as4) ok.
But when I' trying to send a self-test (bypassing SMP) - as2 transmission works ok, however as4 ones fails with a following message: "Transport protocol 'peppol-transport-as4-v2_0' not supported."

2019-12-27 15:14:22,200 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2019-12-27 15:14:22,200 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0 
2019-12-27 15:14:22,200 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 

2019-12-27 15:14:22,479 WARN [no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour. 
2019-12-27 15:14:22,897 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Transport protocol 'peppol-transport-as4-v2_0' not supported. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Transport protocol 'peppol-transport-as4-v2_0' not supported.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: Transport protocol 'peppol-transport-as4-v2_0' not supported.
	at no.difi.oxalis.outbound.transmission.MessageSenderFactory.getSender(MessageSenderFactory.java:110)
	at no.difi.oxalis.outbound.transmission.MessageSenderFactory.getMessageSender(MessageSenderFactory.java:123)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:148)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1

Transport AS4 protocol is not even listed in Prioritized list.
According to Oxalis AS4 setup video - https://vimeo.com/366420949 - it should.

Is it possible to explain a bit more how Oxalis is getting a list of transport protocols to use for a particular transmission.

**Comment by odha** [comment]
Hi, 
Did you add Oxalis-AS4 to the setup of your Oxalis? That's the component that "adds" AS4-support to Oxalis, if i'm not mistaken.

**Comment by FrodeBjerkholt** [comment]
Failed to reproduce this issue.
