### ISSUE TITLE
AS4 Nullpointer Exception with Tomcat version 9.0.30.0

### ISSUE THREAD

**Issue by TTD93** [difi/Oxalis-AS4#53]
Hi, I'm using webapp-runner version 9.0.30.0 (so same version of Tomcat) to deploy the application. I've just started implementing it so I might have done something wrong. When I tried to test if I've set it up correctly by running a test file with the following command: 

`java -jar target/oxalis-standalone.jar -f ./oxalis-commons/src/test/resources/peppol-bis-invoice-sbdh.xml -u http://localhost:8080/as4 -cert ./.oxalis/test_certificate.cer --protocol peppol-transport-as4-v2_0` 

I got the following error: 
```

2020-01-13 18:53:13,635 INFO [no.difi.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value './.oxalis/'. 
2020-01-13 18:53:13,637 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: ./.oxalis 
2020-01-13 18:53:13,638 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: ./.oxalis 
2020-01-13 18:53:13,638 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: ./.oxalis/oxalis.conf 
2020-01-13 18:53:13,642 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF:  
2020-01-13 18:53:13,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound_files 
2020-01-13 18:53:13,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: null 
2020-01-13 18:53:13,920 INFO [no.difi.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value './.oxalis/'. 
2020-01-13 18:53:13,920 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: ./.oxalis 
2020-01-13 18:53:13,921 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: ./.oxalis 
2020-01-13 18:53:13,921 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: ./.oxalis/oxalis.conf 
2020-01-13 18:53:13,922 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20 
2020-01-13 18:53:13,922 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2 
2020-01-13 18:53:13,922 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0 
2020-01-13 18:53:13,922 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF:  
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound_files 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: null 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:  
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => PATH: ApCertificate.pfx 
2020-01-13 18:53:13,923 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: 'VYwqqdbgj-_Knuf6KeFcjLPDCgXi4!8GKfNoiqF3VLpnaJVCvJ' 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: 1 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: 'VYwqqdbgj-_Knuf6KeFcjLPDCgXi4!8GKfNoiqF3VLpnaJVCvJ' 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: google_storage 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: google_storage 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: google_storage 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: google_storage 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: null 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50 
2020-01-13 18:53:13,924 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS4 => HOSTNAME:  
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS4 => MSGID_GENERATOR: default 
2020-01-13 18:53:13,925 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS4 => TYPE: peppol 
2020-01-13 18:53:13,926 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: null 
2020-01-13 18:53:13,926 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback 
2020-01-13 18:53:13,975 INFO [no.difi.oxalis.commons.security.CertificateModule] Certificate subject: C=NO, O=Luca Labs AS, OU=PEPPOL TEST AP, CN=PNO000331 
2020-01-13 18:53:13,976 INFO [no.difi.oxalis.commons.security.CertificateModule] Certificate issuer: CN=PEPPOL ACCESS POINT TEST CA - G2, OU=FOR TEST ONLY, O=OpenPEPPOL AISBL, C=BE 
2020-01-13 18:53:18,084 INFO [no.difi.vefa.peppol.security.ModeDetector] Detected mode: TEST 
2020-01-13 18:53:18,096 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles: 
2020-01-13 18:53:18,097 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0 
2020-01-13 18:53:18,097 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2020-01-13 18:53:18,097 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0 
2020-01-13 18:53:18,097 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 


2020-01-13 18:53:18,298 WARN [no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour. 
2020-01-13 18:53:18,797 ERROR [no.difi.oxalis.commons.error.QuietErrorTracker] [e087fe49-153d-49d7-831d-6b50d615ee74] null 
java.lang.NullPointerException: null
        at no.difi.oxalis.as4.util.PolicyUtil.getPolicy(PolicyUtil.java:30)
        at no.difi.oxalis.as4.util.PolicyUtil.getPolicy(PolicyUtil.java:22)
        at no.difi.oxalis.as4.outbound.As4MessageSender.getService(As4MessageSender.java:136)
        at no.difi.oxalis.as4.outbound.As4MessageSender.createDispatch(As4MessageSender.java:120)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:71)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-01-13 18:53:18,797 ERROR [eu.sendregning.oxalis.Main] Execution failed: java.lang.NullPointerException 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: java.lang.NullPointerException: null
        at no.difi.oxalis.as4.util.PolicyUtil.getPolicy(PolicyUtil.java:30)
        at no.difi.oxalis.as4.util.PolicyUtil.getPolicy(PolicyUtil.java:22)
        at no.difi.oxalis.as4.outbound.As4MessageSender.getService(As4MessageSender.java:136)
        at no.difi.oxalis.as4.outbound.As4MessageSender.createDispatch(As4MessageSender.java:120)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:71)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
As far as I found on similar cases it was caused by outdated Tomcat versions. Any idea on why this happens? I've also used other tests files than the one in the command line..

**Comment by TTD93** [comment]
Worked after i reverted back to version RC9

**Comment by FrodeBjerkholt** [comment]
The correct way to use the standalone with AS4 is:

java -classpath "standalone/*;as4/*" eu.sendregning.oxalis.Main [followd by the argument like -f c:\some-invoice.xml]

**Comment by TTD93** [comment]
We needed the whole project wrapped up in a single war file. So we've added the AS4 Extension directly into the Oxalis project as a dependency, so standalone.jar now works without extracting the AS4 jar files into a own dir structure. I'm just not sure why it didn't work in RC10?

**Comment by FrodeBjerkholt** [comment]
The NullPointerException is probably thrown if the PolicyUtil do not find the policy.xml file on the classpath. Maybe the policy.xml is missing in the WAR file?

**Comment by TTD93** [comment]
Both eDeliveryAS4Policy.xml and eDeliveryAS4Policy_BST.xml is included.
