### ISSUE TITLE
as/4 standalone JNI error

### ISSUE THREAD

**Issue by cp-deha** [difi/Oxalis-AS4#57]
Got the following error when trying to launch the standalone for as/4

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more

It seems some dependencies are missing, but I can try to follow the installation manual over and over again. I don't see the error.
Could you please give me more information to fix the issue?

**Comment by FrodeBjerkholt** [comment]
Can you look inside the oxalis-standalone.jar and see if you can locate the file under /joptsimple/OptionSpec.class - I find it there. 
You should download oxalis-standalone.jar from https://github.com/difi/oxalis/releases

**Comment by midhunmohan** [comment]
`java -cp oxalis-distribution-4.1.0-distro/bin/*:oxalis-as4-4.1.0-SNAPSHOT-dist/* eu.sendregning.oxalis.Main -f  sample-file.xml`

you can get the needed files in the classpath using the following links
[https://repo1.maven.org/maven2/no/difi/oxalis/oxalis-distribution/4.1.0/oxalis-distribution-4.1.0-distro.zip](https://repo1.maven.org/maven2/no/difi/oxalis/oxalis-distribution/4.1.0/oxalis-distribution-4.1.0-distro.zip)
&
[https://github.com/difi/Oxalis-AS4/releases/download/4.1.0-RC11/oxalis-as4-4.1.0-SNAPSHOT-dist.zip](https://github.com/difi/Oxalis-AS4/releases/download/4.1.0-RC11/oxalis-as4-4.1.0-SNAPSHOT-dist.zip)

oxalis config, it will take from the OXALIS_HOME env variable, hope this helps @cp-deha
