### ISSUE TITLE
java.lang.NullPointerException at no.difi.oxalis.as4.util.PolicyUtil.getPolicy

### ISSUE THREAD

**Issue by bluejudas** [difi/Oxalis-AS4#59]
Hi, 

I have made an application that sends messages. 
The application is compiled with Oxalis 4.1 and AS4 4.1.0-SNAPSHOT.
At startup I get this in the Oxalis log.

`2020-01-21 13:30:31,736 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] => peppol-transport-as4-v2_0
`

When trying to send with AS4 i get this exception. AS2  works fine.

```
SEVERE: Failure transmitting message, for file D:\Oxalis\out\{CF2C65C9-6FA3-4E1E-BBA5-FCEC9EB6F75A}.xml
java.lang.NullPointerException
	at no.difi.oxalis.as4.util.PolicyUtil.getPolicy(PolicyUtil.java:30)
	at no.difi.oxalis.as4.util.PolicyUtil.getPolicy(PolicyUtil.java:22)
	at no.difi.oxalis.as4.outbound.As4MessageSender.getService(As4MessageSender.java:136)
	at no.difi.oxalis.as4.outbound.As4MessageSender.createDispatch(As4MessageSender.java:120)
	at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:71)
	at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
	at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
```

**Comment by TTD93** [comment]
Seems like builder in PolicyService returns null `PolicyBuilder builder = bus.getExtension(PolicyBuilder.class);`

**Comment by FrodeBjerkholt** [comment]
Your stacktrace tells me that you are not using the latest RC. Can you try upgrading first, please?

**Comment by FrodeBjerkholt** [comment]
I got the same problem with bus.getExtension(PolicyBuilder.class) when using maven-shade-plugin, because of CXF issues. I fixed it by following [this](https://cxf.apache.org/docs/bundling-cxf-into-single-jar-with-maven-shade-plugin.html).

**Comment by ri4a** [comment]
RC9 does not have this problem, but upgrading to RC12 we ran into it too.

**Comment by FrodeBjerkholt** [comment]
RC10 was the first to use policy files.

**Comment by bluejudas** [comment]
I upgraded to RC12. Exception is gone.
Well iI get "Invalid message digest.", but that is 4.1 => 4.0.2 issue ?

**Comment by FrodeBjerkholt** [comment]
I have not tested with 4.0.2. Please try with 4.0.3, 4.0.4 or 4.1.0

**Comment by TTD93** [comment]
Thanks, fixed the problem with the CXF issues by using the fix you suggested!
