### ISSUE TITLE
Oxalis standalone issue

### ISSUE THREAD

**Issue by jeroenc89** [difi/Oxalis-AS4#62]
Hi all

I'm facing some issues when testing the Oxalis standalone steps in the test-bed.
Whenever I call the command I receive this error:
_Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpUriRequest
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.methods.HttpUriRequest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more_

Command used:
_java -classpath "standalone/*;as4/*" eu.sendregning.oxalis.Main -f C:/xxx/Oxalis/AS4/standalone/outbound.xml -r 0088:TBCNTRL00002 -s 9956:xxxxx_ 
(did replace some sensitive info with 'x')

I'm running Oxalis on a Windows Server 2016.
Tested with both jre1.8.0_191 and jre1.8.0_241.
Tested with a command prompt with administrator privileges.
Oxalis AS4 inbound invoices are working.

Thanks in advance!

**Comment by jeroenc89** [comment]
Was using the wrong .jar file...
Using this one now: https://github.com/difi/oxalis/releases
