### ISSUE TITLE
Unable to create injector

### ISSUE THREAD

**Issue by amarianski** [difi/Oxalis-AS4#68]
Hi,

we are trying to install AS4 in many ways. Finally we get to this:
[2020-01-30 19:15:30] [info] 19:15:30.690 [main] INFO n.d.o.c.f.detector.JndiHomeDetector - Using Oxalis folder specified as JNDI path 'java:comp/env/OXALIS_HOME' with value '/opt/oxalis'.
[2020-01-30 19:15:30] [info] 19:15:30.700 [main] INFO n.d.o.c.filesystem.FileSystemModule - Home folder: /opt/oxalis
[2020-01-30 19:15:30] [info] 19:15:30.701 [main] INFO n.d.o.c.filesystem.FileSystemModule - Configuration folder: /opt/oxalis
[2020-01-30 19:15:30] [info] 19:15:30.702 [main] INFO n.d.o.commons.config.ConfigModule - Configuration file: /opt/oxalis/oxalis.conf
[2020-01-30 19:15:30] [info] 19:15:30.718 [main] INFO n.d.o.c.settings.SettingsBuilder - File system => CONF:
[2020-01-30 19:15:30] [info] 19:15:30.719 [main] INFO n.d.o.c.settings.SettingsBuilder - File system => INBOUND: /var/peppol/IN
[2020-01-30 19:15:30] [info] 19:15:30.720 [main] INFO n.d.o.c.settings.SettingsBuilder - File system => PLUGIN: oxalis-plugin
[2020-01-30 19:15:31] [info] 19:15:31.797 [main] ERROR n.d.o.i.OxalisGuiceContextListener - Unable to create injector, see the following errors:
[2020-01-30 19:15:31] [info] 1) No implementation for no.difi.oxalis.as4.outbound.ActionProvider was bound.
[2020-01-30 19:15:31] [info] while locating no.difi.oxalis.as4.outbound.ActionProvider
[2020-01-30 19:15:31] [info] for the 3rd parameter of no.difi.oxalis.as4.common.As4CommonModule.getPolicyService(As4CommonModule.java:63)
[2020-01-30 19:15:31] [info] at no.difi.oxalis.as4.common.As4CommonModule.getPolicyService(As4CommonModule.java:63)
[2020-01-30 19:15:31] [info] 1 error
[2020-01-30 19:15:31] [info] com.google.inject.CreationException: Unable to create injector, see the following errors:
[2020-01-30 19:15:31] [info] 1) No implementation for no.difi.oxalis.as4.outbound.ActionProvider was bound.
[2020-01-30 19:15:31] [info] while locating no.difi.oxalis.as4.outbound.ActionProvider
[2020-01-30 19:15:31] [info] for the 3rd parameter of no.difi.oxalis.as4.common.As4CommonModule.getPolicyService(As4CommonModule.java:63)
[2020-01-30 19:15:31] [info] at no.difi.oxalis.as4.common.As4CommonModule.getPolicyService(As4CommonModule.java:63)
[2020-01-30 19:15:31] [info] 1 error 

don't know how to solve, have you got any tips, ideas how can we go further? Thank you.

**Comment by FrodeBjerkholt** [comment]
Which version of the oxalis-as4 are you using?

**Comment by amarianski** [comment]
Ok it's working :)
