### ISSUE TITLE
Sockets not closing properly

### ISSUE THREAD

**Issue by jonassss** [difi/Oxalis-AS4#74]
Hi,

We are experiencing a problem where open sockets are not properly closed after transmission.
Since we have separated the inbound and outbound functionality by routing the respective requests to separate containers, and we are only observing this on the outbound containers, we can isolate this issue to the outbound part

The stacktrace looks like this:
`no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
    at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:91)
    at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
    at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
    at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
    at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
    at no.sr.ringo.oxalis.OxalisDocumentSender.sendDocument(OxalisDocumentSender.java:46)
    at no.sr.ringo.usecase.SendQueuedMessagesUseCase.lockQueueRowAndSendMessage(SendQueuedMessagesUseCase.java:201)
    at no.sr.ringo.persistence.guice.jdbc.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:84)
    at no.sr.ringo.usecase.SendQueuedMessagesUseCase.handleSingleQueuedMessage(SendQueuedMessagesUseCase.java:163)
    at no.sr.ringo.usecase.SendQueuedMessagesUseCase.handleSingleQueuedMessage(SendQueuedMessagesUseCase.java:125)
    at no.sr.ringo.resource.OutboxResource.postXml(OutboxResource.java:244)
    at sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
    at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:592)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:500)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.ws.soap.SOAPFaultException: java.io.FileNotFoundException: /opt/apache-tomcat-9.0.12/webapps/peppol/WEB-INF/lib/jcl-over-slf4j-1.7.26.jar (Too many open files)
    at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
    at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:88)
    ... 55 common frames omitted`

However, when we inspect the open files on the server, we see that this is caused by open sockets (which are files on linux).

**Comment by FrodeBjerkholt** [comment]
Thank you for the information. I will start to look at the problem.

**Comment by FrodeBjerkholt** [comment]
I see that the dispatcher (and client) i not closed. Hopefully closing these, will fix the problem.
I will most likely make a new release as soon as possible.

**Comment by FrodeBjerkholt** [comment]
I have now released 4.1.2 that hopefully fixes the problem.
