### ISSUE TITLE
Cannot find key for certificate while receiving message from CEF Connectivity test

### ISSUE THREAD

**Issue by ea1** [difi/Oxalis-AS4#80]
We have setup Oxalis 4.1.1 with AS4 module 4.13 and trying to run through the first step in CEF connectivitiy test.

Message is rejected on our end and we can in the log see: 
**Cannot find key for certificate in keystore of type [JKS] from provider [SUN version 1.8] with size [1] and aliases: {ceftestparty98gw}**
and
**Cannot find key for certificate**

2020-02-06 12:09:41,998  DEBUG [org.apache.wss4j.dom.processor.EncryptedKeyProcessor] Found encrypted key element 
2020-02-06 12:09:41,998  DEBUG [org.apache.wss4j.dom.util.X509Util] Sym Enc Algo: http://www.w3.org/2009/xmlenc11#rsa-oaep 
2020-02-06 12:09:42,045  ERROR [org.apache.wss4j.common.crypto.Merlin] Cannot find key for certificate in keystore of type [JKS] from provider [SUN version 1.8] with size [1] and aliases: {ceftestparty98gw} 

Caused by: org.apache.wss4j.common.ext.WSSecurityException: Cannot find key for certificate
	at org.apache.wss4j.dom.processor.EncryptedKeyProcessor.getPrivateKey(EncryptedKeyProcessor.java:270)
	at org.apache.wss4j.dom.processor.EncryptedKeyProcessor.handleToken(EncryptedKeyProcessor.java:226)
	at org.apache.wss4j.dom.processor.EncryptedKeyProcessor.handleToken(EncryptedKeyProcessor.java:90)
	at org.apache.wss4j.dom.engine.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:340)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:320)

Caused by: org.apache.wss4j.common.ext.WSSecurityException: Cannot find key for certificate
	at org.apache.wss4j.common.crypto.Merlin.getPrivateKey(Merlin.java:624)
	at org.apache.wss4j.dom.processor.EncryptedKeyProcessor.getPrivateKey(EncryptedKeyProcessor.java:266)

It seems like all certificates are loaded successfully:

12:06:55.985 [main] INFO  n.d.o.c.settings.SettingsBuilder - Key store => PATH: ceftestparty98gwkeystore.jks
12:06:55.985 [main] INFO  n.d.o.c.settings.SettingsBuilder - Key store => PASSWORD: testxxx
12:06:55.985 [main] INFO  n.d.o.c.settings.SettingsBuilder - Key store => KEY_ALIAS: ceftestparty98gw
12:06:55.985 [main] INFO  n.d.o.c.settings.SettingsBuilder - Key store => KEY_PASSWORD: testxxx

2020-02-06 12:06:56,094  INFO [no.difi.oxalis.commons.security.CertificateModule] Certificate subject: C=BE, O=eDelivery, CN=ceftestparty98gw 
2020-02-06 12:06:56,110  INFO [no.difi.oxalis.commons.security.CertificateModule] Certificate issuer: C=BE, O=eDelivery, CN=ceftestparty98gw 

2020-02-06 12:07:00,326  INFO [no.difi.oxalis.as4.common.MerlinProvider] Loading TRUSTSTORE: C:\oxalis\ceftestparty98gwtruststore.jks 
2020-02-06 12:07:00,326  INFO [no.difi.oxalis.as4.common.MerlinProvider] Adding ceftestparty98gw to truststore 
2020-02-06 12:07:00,326  INFO [no.difi.oxalis.as4.common.MerlinProvider] Adding cefsupportgw to truststore 

Using java keystore explorer we can see that our keystore jks file has one alias and one certificate complete with a private key and password on both are the same.

Our trust store jks contains two aliases one for cef support and one for our test party. Both contains only a public key and no private key.

The throwing error line is:
org.apache.wss4j.common.crypto.Merlin.getPrivateKey(Merlin.java:624)
which seems to hint that it is not able to find a private key in a store.

It is hard for us to read from the errors logged in the log file which keystore it is trying to extract a private key.

Based on your experience should the trust store contain a private key?

**Comment by FrodeBjerkholt** [comment]
Can you add the command line you are using when sending to CEF?

**Comment by ea1** [comment]
This was on the first step "Testbed sends to testing AP" where we should receive a message from CEF.

**Comment by FrodeBjerkholt** [comment]
Now I am confused. Are you doing the CEF connectivity test or are you trying the OpenPEPPOL TestBed?

**Comment by ea1** [comment]
We are trying to run the "AS4 Conformance/onboarding test suite. Version 1.0" in the test bed.

**Comment by FrodeBjerkholt** [comment]
Ok - Then I know. I see that you have configured oxlias with the CEF-connectivity test certificates. These will not work with the test bed. You need to acquire a test certificate from PEPPOL and use that in your AP. For the test bed, there is no need for a truststore.

**Comment by FrodeBjerkholt** [comment]
But since you obviously have succeeded to open the test bed test suite, you probably have such a certificate already?  Your oxalis.xonf should then look similar to this:

```properties
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=peppol-g2-test-2018-05-28.jks
     password = xxx
     key.alias = ap
     key.password = xxx
}

# The folder where the incoming messages will be stored
oxalis.path.inbound = /var/peppol/IN

# Optional
oxalis.logging.config=logback.xml
```

**Comment by ea1** [comment]
Thanks! 
We received the message from OpenPEPPOL Test bed now!
