### ISSUE TITLE
Could not find a resolver for URI

### ISSUE THREAD

**Issue by ri4a** [difi/Oxalis-AS4#86]
Hi,

We are getting the following errors when our sending AP is running multiple jobs in parallel:

```
java.lang.RuntimeException: Failed to send message
    <snip>
Caused by: javax.xml.ws.soap.SOAPFaultException: javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:d67b316c-8ead-4574-8747-f02bdf6df1da@localhost and Base null
        at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:95)
        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:87)
        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
        ... 12 more
Caused by: org.apache.cxf.interceptor.Fault: javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:d67b316c-8ead-4574-8747-f02bdf6df1da@localhost and Base null
        at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.doSignBeforeEncrypt(AsymmetricBindingHandler.java:237)
        at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.handleBinding(AsymmetricBindingHandler.java:117)
        at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessageInternal(PolicyBasedWSS4JOutInterceptor.java:185)
        at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:109)
        at org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal.handleMessage(PolicyBasedWSS4JOutInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
        ... 19 more
Caused by: org.apache.wss4j.common.ext.WSSecurityException: javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:d67b316c-8ead-4574-8747-f02bdf6df1da@localhost and Base null
Original Exception was javax.xml.crypto.dsig.XMLSignatureException: javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:d67b316c-8ead-4574-8747-f02bdf6df1da@localhost and Base null
        at org.apache.wss4j.dom.message.WSSecSignature.computeSignature(WSSecSignature.java:621)
        at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.doSignature(AsymmetricBindingHandler.java:743)
        at org.apache.cxf.ws.security.wss4j.policyhandlers.AsymmetricBindingHandler.doSignBeforeEncrypt(AsymmetricBindingHandler.java:180)
        ... 30 more
Caused by: javax.xml.crypto.dsig.XMLSignatureException: javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:d67b316c-8ead-4574-8747-f02bdf6df1da@localhost and Base null
        at org.apache.jcp.xml.dsig.internal.dom.DOMReference.dereference(DOMReference.java:418)
        at org.apache.jcp.xml.dsig.internal.dom.DOMReference.digest(DOMReference.java:352)
        at org.apache.jcp.xml.dsig.internal.dom.DOMXMLSignature.digestReference(DOMXMLSignature.java:486)
        at org.apache.jcp.xml.dsig.internal.dom.DOMXMLSignature.sign(DOMXMLSignature.java:371)
        at org.apache.wss4j.dom.message.WSSecSignature.computeSignature(WSSecSignature.java:614)
        ... 32 more
Caused by: javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:d67b316c-8ead-4574-8747-f02bdf6df1da@localhost and Base null
        at org.apache.jcp.xml.dsig.internal.dom.DOMURIDereferencer.dereference(DOMURIDereferencer.java:117)
        at org.apache.jcp.xml.dsig.internal.dom.DOMReference.dereference(DOMReference.java:414)
        ... 36 more
Caused by: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:d67b316c-8ead-4574-8747-f02bdf6df1da@localhost and Base null
        at org.apache.xml.security.utils.resolver.ResourceResolver.internalGetInstance(ResourceResolver.java:113)
        at org.apache.xml.security.utils.resolver.ResourceResolver.getInstance(ResourceResolver.java:74)
        at org.apache.jcp.xml.dsig.internal.dom.DOMURIDereferencer.dereference(DOMURIDereferencer.java:109)
        ... 37 more


```

This we do not see this happening when we throttle down to a single job per server, but that is very slow...

What could we do to fix this?

Thanks!

Best regards,

Michael from Storecove

**Comment by FrodeBjerkholt** [comment]
First, I will try to reproduce the problem. Can I expect to get the same problem if I try to send multiple messages in parallel?

**Comment by ri4a** [comment]
Yes, I think so. Sending four in parallel already leads to jobs failing very often.

**Comment by FrodeBjerkholt** [comment]
Can you try sending with the standalone sender using the -repeat argument? By default it runs 50 tasks in parallel and I do not encounter the same problem.

**Comment by FrodeBjerkholt** [comment]
Can you also enable debug logging for org.apache.xml.security.utils.resolver.ResourceResolver - I see that it 
                LOG.debug("check resolvability by class {}", resolverTmp.getClass().getName());

It will be interesting to see the list when you get the problem.

When I am debugging I see that it is the ResolverAttachment class that resolves the URI

**Comment by FrodeBjerkholt** [comment]
I have also tested with a simple program running multiple threads using the Transmiter interface without reproducing the error.

**Comment by ri4a** [comment]
I have some more info from oxalis.log:

```
2020-02-10 14:22:15,329 DEBUG [org.apache.xml.security.utils.resolver.ResourceResolver] [] Registered resolver: org.apache.wss4j.dom.resolvers.ResolverAttachment@2c4ee0af
```

and then

```
2020-02-10 14:22:15,429 DEBUG [org.apache.xml.security.utils.resolver.ResourceResolver] [] check resolvability by class org.apache.xml.security.utils.resolver.ResourceResolver 
2020-02-10 14:22:15,429 DEBUG [org.apache.xml.security.utils.resolver.implementations.ResolverFragment] [] Do not seem to be able to resolve reference: "cid:45fe1ae5-55da-4220-b07c-11008790c60f@localhost" 
2020-02-10 14:22:15,429 DEBUG [org.apache.xml.security.utils.resolver.ResourceResolver] [] check resolvability by class org.apache.xml.security.utils.resolver.ResourceResolver 
2020-02-10 14:22:15,429 DEBUG [org.apache.xml.security.utils.resolver.implementations.ResolverLocalFilesystem] [] I was asked whether I can resolve cid:45fe1ae5-55da-4220-b07c-11008790c60f@localhost 
2020-02-10 14:22:15,429 DEBUG [org.apache.xml.security.utils.resolver.implementations.ResolverLocalFilesystem] [] null 
java.lang.NullPointerException: null
    <snip: exception is caught>
2020-02-10 14:22:15,430 DEBUG [org.apache.xml.security.utils.resolver.implementations.ResolverLocalFilesystem] [] But I can't 
2020-02-10 14:22:15,430 DEBUG [org.apache.xml.security.utils.resolver.ResourceResolver] [] check resolvability by class org.apache.xml.security.utils.resolver.ResourceResolver 
2020-02-10 14:22:15,430 DEBUG [org.apache.xml.security.utils.resolver.ResourceResolver] [] check resolvability by class org.apache.xml.security.utils.resolver.ResourceResolver 
2020-02-10 14:22:15,430 DEBUG [org.apache.xml.security.utils.resolver.implementations.ResolverDirectHTTP] [] I was asked whether I can resolve cid:45fe1ae5-55da-4220-b07c-11008790c60f@localhost 
2020-02-10 14:22:15,430 DEBUG [org.apache.xml.security.utils.resolver.implementations.ResolverDirectHTTP] [] I state that I can't resolve cid:45fe1ae5-55da-4220-b07c-11008790c60f@localhost 
2020-02-10 14:22:15,431 ERROR [org.apache.wss4j.dom.message.WSSecSignature] [] javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:45fe1ae5-55da-4220-b07c-11008790c60f@localhost and Base null 
javax.xml.crypto.dsig.XMLSignatureException: javax.xml.crypto.URIReferenceException: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:45fe1ae5-55da-4220-b07c-11008790c60f@localhost and Base null
        at org.apache.jcp.xml.dsig.internal.dom.DOMReference.dereference(DOMReference.java:418)
        <snip>
```

Since the default resolvers are

- [registerDefaultResolvers](http://svn.apache.org/viewvc/santuario/xml-security-java/tags/xmlsec-2.1.4/src/main/java/org/apache/xml/security/utils/resolver/ResourceResolver.java?revision=1863159&view=markup#l257)

(and ResolverXPointer does not log anything), it seems only the default resolvers are called and the previously registered ResolverAttachment resolver is not in the resolverList. Otherwise,

- [engineCanResolveURI](http://svn.apache.org/viewvc/webservices/wss4j/tags/wss4j-2.2.4/ws-security-dom/src/main/java/org/apache/wss4j/dom/resolvers/ResolverAttachment.java?revision=1863471&view=markup#l48)

would have returned `true` when called with `cid:45fe1ae5-55da-4220-b07c-11008790c60f@localhost`.

Any ideas?

**Comment by FrodeBjerkholt** [comment]
Are you using Tomcat? And are you running more than one war, ear etc on the same instance?

**Comment by ri4a** [comment]
We don't use Tomcat, but we do run multiple JARs through their manifest Main-Class: on the same instance.

**Comment by FrodeBjerkholt** [comment]
I don't know why you experience this, but it seems that WSS4J has issues related to classloading and static initializing.

**Comment by senikk** [comment]
I have seen the same type of errors in our logs with AS4 4.1.3 version:

`07:37:58.092 [main] DEBUG org.apache.jcp.xml.dsig.internal.dom.DOMReference - Reference digesting completed
07:37:58.092 [main] DEBUG org.apache.xml.security.utils.resolver.ResourceResolver - check resolvability by class org.apache.xml.security.utils.resolver.ResourceResolver
07:37:58.093 [main] DEBUG org.apache.xml.security.utils.resolver.implementations.ResolverFragment - Do not seem to be able to resolve reference: "cid:307a2b0a-c264-4e1f-b10f-9e1d6aa3fe4d@unimicro.no"
07:37:58.093 [main] DEBUG org.apache.xml.security.utils.resolver.ResourceResolver - check resolvability by class org.apache.xml.security.utils.resolver.ResourceResolver
07:37:58.093 [main] DEBUG org.apache.xml.security.utils.resolver.implementations.ResolverLocalFilesystem - I was asked whether I can resolve cid:307a2b0a-c264-4e1f-b10f-9e1d6aa3fe4d@unimicro.no
07:37:58.093 [main] DEBUG org.apache.xml.security.utils.resolver.implementations.ResolverLocalFilesystem - null
java.lang.NullPointerException: null
	at org.apache.xml.security.utils.resolver.implementations.ResolverLocalFilesystem.engineCanResolveURI(ResolverLocalFilesystem.java:122)
	at org.apache.xml.security.utils.resolver.ResourceResolver.canResolve(ResourceResolver.java:337)
	at org.apache.xml.security.utils.resolver.ResourceResolver.internalGetInstance(ResourceResolver.java:95)
	at org.apache.xml.security.utils.resolver.ResourceResolver.getInstance(ResourceResolver.java:74)
	at org.apache.jcp.xml.dsig.internal.dom.DOMURIDereferencer.dereference(DOMURIDereferencer.java:109)
	at org.apache.jcp.xml.dsig.internal.dom.DOMReference.dereference(DOMReference.java:414)
	at org.apache.jcp.xml.dsig.internal.dom.DOMReference.digest(DOMReference.java:352)
	at org.apache.jcp.xml.dsig.internal.dom.DOMXMLSignature.digestReference(DOMXMLSignature.java:486)
	at org.apache.jcp.xml.dsig.internal.dom.DOMXMLSignature.sign(DOMXMLSignature.java:371)
	at org.apache.wss4j.dom.message.WSSecSignature.computeSignature(WSSecSignature.java:614)
`

In other cases it returns "I state that I can't resolve" instead of failing with nullpointerexception. Both these cases is from the same sender pod in our Kubernetes cluster. 

So the first one of these have failed with NullPointerException and the other hasn't, that seems very strange
cid:307a2b0a-c264-4e1f-b10f-9e1d6aa3fe4d@unimicro.no 
cid:e6a15c9f-e772-4938-a47a-b32ad9787c83@unimicro.no

`07:38:08.445 [main] DEBUG org.apache.xml.security.utils.resolver.implementations.ResolverDirectHTTP - I was asked whether I can resolve cid:e6a15c9f-e772-4938-a47a-b32ad9787c83@unimicro.no
07:38:08.445 [main] DEBUG org.apache.xml.security.utils.resolver.implementations.ResolverDirectHTTP - I state that I can't resolve cid:e6a15c9f-e772-4938-a47a-b32ad9787c83@unimicro.no`

**Comment by ri4a** [comment]
The NullPointerExceptions are caught, so these are not a problem. It then continues to try other resolvers until all resolvers have failed. The required ResolverAttachment is not in the list of resolvers, that is the problem.

**Comment by FrodeBjerkholt** [comment]
The AttachmentResolver is statically initialized once in WSSConfig:

```java
    static {
        try {
            Transform.register(WSConstants.SWA_ATTACHMENT_CIPHERTEXT_TRANS,
                    AttachmentCiphertextTransform.class);
        } catch (Exception e) {
            LOG.debug(e.getMessage(), e);
        }

        ResourceResolver.register(new ResolverAttachment(), false);
    }
```

And the default resolvers in the resolverList in the ResourceResolver is initialized statically in org.apache.xml.security.Init.init() 
So I am pretty sure that this is some kind of classloading issue.

**Comment by ri4a** [comment]
I agree. It seems our worker does not like jobs that bootstrap static contexts.

Instead of running multiple jobs on a single worker, we now run a single job on multiple workers.

Closing, thanks for all your help!
