### ISSUE TITLE
Update to 4.1.1/4.1.3 => No transmission is provided. (standalone error: participant not found in SML)

### ISSUE THREAD

**Issue by sandoor** [difi/Oxalis-AS4#89]
Hi,

Previous versions worked fine, I only upped the versions to the latest one. 
Testbed AS4 conformance not passing anymore, because of a sending error...

I've read the thread with a similar issue with CEF, but that was of no help.

**Version**
<pre>
Oxalis.AS4 Version : 4.1.3

version.oxalis: 4.1.1
version.java: 1.8.0_231
mode: TEST
certificate.issuer: CN=PEPPOL ACCESS POINT TEST CA - G2,OU=FOR TEST ONLY,O=OpenPEPPOL AISBL,C=BE
certificate.expired: false
build.id: 2c4b36ab050ff68971e719004ce454195e5c3da1
build.tstamp: 06.02.2020 @ 10:35:50 UTC
</pre>

**Command**
<pre>
"%JAVA_HOME%\bin\java.exe" -classpath "C:\PEPPOL\bin\OxalisSender\*;C:\PEPPOL\bin\oxalis-as4-4.1.3-dist\*" eu.sendregning.oxalis.Main --protocol peppol-transport-as4-v2_0 -f "%OXALIS_HOME%\OUT\test.xml"
</pre>

**Oxalis config**
<pre>
# Oxalis config
oxalis.keystore {
     path="C:/PEPPOL/cert/oxalis-keystore.jks"
     password = ***
     key.alias = oxalis
     key.password = ***
}

oxalis.truststore.path="C:/PEPPOL/cert/truststore.jks"
oxalis.truststore.password = ***

# The relative name of the directory holding plugin
#oxalis.path.plugin = oxalis-plugin

# Signals to Oxalis that we should look for plugin
#oxalis.persister.receipt = plugin

# Where to store inbound files
oxalis.path.inbound = "C:/PEPPOL/OxalisTransfer/IN"
oxalis.logging.config = "C:/PEPPOL/logback.xml"

oxalis.java.http.proxyHost = intproxy.blah.com
oxalis.java.http.proxyPort = 8080
oxalis.java.https.proxyHost = intproxy.blah.com
oxalis.java.https.proxyPort = 8080
</pre>

**LOG**
<pre>
2020-02-11 14:25:33 - http-outgoing-1 << HTTP/1.1 200 OK
2020-02-11 14:25:33 - http-outgoing-1 << Server: nginx/1.16.1
2020-02-11 14:25:33 - http-outgoing-1 << Content-Type: application/ocsp-response
2020-02-11 14:25:33 - http-outgoing-1 << Content-Length: 1790
2020-02-11 14:25:33 - http-outgoing-1 << content-transfer-encoding: binary
2020-02-11 14:25:33 - http-outgoing-1 << Cache-Control: max-age=414633, public, no-transform, must-revalidate
2020-02-11 14:25:33 - http-outgoing-1 << Last-Modified: Sun, 9 Feb 2020 08:35:52 +00:00
2020-02-11 14:25:33 - http-outgoing-1 << Expires: Sun, 16 Feb 2020 08:35:52 +00:00
2020-02-11 14:25:33 - http-outgoing-1 << Date: Tue, 11 Feb 2020 13:25:19 GMT
2020-02-11 14:25:33 - http-outgoing-1 << Accept-Ranges: none
2020-02-11 14:25:33 - http-outgoing-1 << Via: 1.1 intproxy.blah.com:8080
2020-02-11 14:25:33 - http-outgoing-1 << Proxy-Connection: keep-alive
2020-02-11 14:25:33 - Connection can be kept alive indefinitely
2020-02-11 14:25:33 - Connection [id: 1][route: {}->http://intproxy.blah.com:8080->http://pki-ocsp.symauth.com:80] can be kept alive indefinitely
2020-02-11 14:25:33 - http-outgoing-1: set socket timeout to 0
2020-02-11 14:25:33 - Connection released: [id: 1][route: {}->http://intproxy.blah.com:8080->http://pki-ocsp.symauth.com:80][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
2020-02-11 14:25:33 - Detected mode: TEST
2020-02-11 14:25:33 - Prioritized list of transport profiles:
2020-02-11 14:25:33 - => peppol-transport-as4-v2_0
2020-02-11 14:25:33 - => busdox-transport-as2-ver1p0r1
2020-02-11 14:25:33 - => busdox-transport-as2-ver2p0
2020-02-11 14:25:33 - => busdox-transport-as2-ver1p0
2020-02-11 14:25:53 - Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre>

**Comment by FrodeBjerkholt** [comment]
I can not answer for oxalis  - only the AS4 plugin. Can try with oxalis-4.1.0 and as4 4.1.3 - Is there any difference?

**Comment by FrodeBjerkholt** [comment]
Can you also check that you havn't got any old jars from a previous version in the installation directories? Or perhaps try to reinstall oxalis + oxalis-as4 from scratch.

**Comment by sandoor** [comment]
- same with 4.1.0.
- no old jars
- disregard issue. IT doing work without notification..... :I
