### ISSUE TITLE
Time out on 4.1.1/AS4 4.1.3

### ISSUE THREAD

**Issue by RvanMaarenApro** [difi/Oxalis-AS4#92]
Found this error this morning in the logs, it seems it is failing not consequently.

Log from oxalis:2020-02-13 09:05:50,168  DEBUG [no.difi.oxalis.as4.util.PolicyService] Policy classpath: /eDeliveryAS4Policy_BST.xml
Log from oxalis:2020-02-13 09:07:58,554  WARN [org.apache.cxf.phase.PhaseInterceptorChain] Interceptor for {oxalis.difi.no/}outbound-service#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now
Log from oxalis:org.apache.cxf.binding.soap.SoapFault: Connection timed out (Connection timed out)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:221)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
Log from oxalis:        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:95)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:87)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
Log from oxalis:        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Log from oxalis:        at java.lang.Thread.run(Thread.java:748)
Log from oxalis:Caused by: com.ctc.wstx.exc.WstxIOException: Connection timed out (Connection timed out)

Previous transmission to same participant went fine on AS4.

Any thougths ?

Regards,

Richard

**Comment by RvanMaarenApro** [comment]
Strange that at some point it wait's for about two minutes and then just halts, AP is retrieved and up seems. Logging if from debug level :

ﾓￔ]XN"ﾣﾇﾵﾍWﾸiﾨ7|Z&ﾔTB8CNﾚ￝9￮￝￡Fxﾉ  
2020-02-14 12:36:16,315  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMReference] Reference object uri = cid:dadedffc-77de-4461-ae5e-c11c06b1f964@localhost 
2020-02-14 12:36:16,315  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMReference] Reference digesting completed 
2020-02-14 12:36:16,316  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMSignatureMethod] Signature provider: SunRsaSign version 1.8 
2020-02-14 12:36:16,316  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMSignatureMethod] Signing with key: sun.security.rsa.RSAPrivateCrtKeyImpl@ffdca9ff 
2020-02-14 12:36:16,316  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMSignatureMethod] JCA Algorithm: SHA256withRSA 
2020-02-14 12:36:16,317  DEBUG [org.apache.xml.security.transforms.Transform] Create URI "http://www.w3.org/2001/10/xml-exc-c14n#" class "class org.apache.xml.security.transforms.implementations.TransformC14NExclusive" 
2020-02-14 12:36:16,317  DEBUG [org.apache.xml.security.transforms.Transform] The NodeList is [ds:CanonicalizationMethod: null] 
2020-02-14 12:36:16,317  DEBUG [org.apache.xml.security.utils.ElementProxy] setElement(ds:CanonicalizationMethod, "null") 
2020-02-14 12:36:16,317  DEBUG [org.apache.jcp.xml.dsig.internal.dom.ApacheCanonicalizer] Created transform for algorithm: http://www.w3.org/2001/10/xml-exc-c14n# 
2020-02-14 12:36:16,317  DEBUG [org.apache.jcp.xml.dsig.internal.dom.ApacheCanonicalizer] isNodeSet() = true 
2020-02-14 12:36:16,317  DEBUG [org.apache.xml.security.utils.ElementProxy] setElement("ec:InclusiveNamespaces", "null") 
2020-02-14 12:36:16,319  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMSignedInfo] Canonicalized SignedInfo: 
2020-02-14 12:36:16,319  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMSignedInfo] <ds:SignedInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:env="http://www.w3.org/2003/05/soap-envelope"><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="env"></ec:InclusiveNamespaces></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"></ds:SignatureMethod><ds:Reference URI="#_9fd71c71-913d-42c5-8517-8e61225048a4"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>2/SVNXm0gZ8KeR7U4LL4pEHKZzW9QzVTpXS003h65a0=</ds:DigestValue></ds:Reference><ds:Reference URI="#_9ee40e00-84d4-4690-9068-e7c6321ca707"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>OpgqhmiA32h29IS8c6+/gzpyrsgfG3zpqdfBSN4v7Fs=</ds:DigestValue></ds:Reference><ds:Reference URI="cid:dadedffc-77de-4461-ae5e-c11c06b1f964@localhost"><ds:Transforms><ds:Transform Algorithm="http://docs.oasis-open.org/wss/oasis-wss-SwAProfile-1.1#Attachment-Content-Signature-Transform"></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>zxzmup1x7iC1ePWM48tI6LrxZrulXgsTFhrE+2UHClA=</ds:DigestValue></ds:Reference></ds:SignedInfo> 
2020-02-14 12:36:16,319  DEBUG [org.apache.jcp.xml.dsig.internal.dom.DOMSignedInfo] Data to be signed/verified:PGRzOlNpZ25lZEluZm8geG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiIHhtbG5zOmVudj0iaHR0cDovL3d3dy53My5vcmcvMjAwMy8wNS9zb2FwLWVudmVsb3BlIj48ZHM6Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI+PGVjOkluY2x1c2l2ZU5hbWVzcGFjZXMgeG1sbnM6ZWM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgUHJlZml4TGlzdD0iZW52Ij48L2VjOkluY2x1c2l2ZU5hbWVzcGFjZXM+PC9kczpDYW5vbmljYWxpemF0aW9uTWV0aG9kPjxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Ij48L2RzOlNpZ25hdHVyZU1ldGhvZD48ZHM6UmVmZXJlbmNlIFVSST0iI185ZmQ3MWM3MS05MTNkLTQyYzUtODUxNy04ZTYxMjI1MDQ4YTQiPjxkczpUcmFuc2Zvcm1zPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiPjwvZHM6VHJhbnNmb3JtPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ij48L2RzOkRpZ2VzdE1ldGhvZD48ZHM6RGlnZXN0VmFsdWU+Mi9TVk5YbTBnWjhLZVI3VTRMTDRwRUhLWnpXOVF6VlRwWFMwMDNoNjVhMD08L2RzOkRpZ2VzdFZhbHVlPjwvZHM6UmVmZXJlbmNlPjxkczpSZWZlcmVuY2UgVVJJPSIjXzllZTQwZTAwLTg0ZDQtNDY5MC05MDY4LWU3YzYzMjFjYTcwNyI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI+PC9kczpUcmFuc2Zvcm0+PC9kczpUcmFuc2Zvcm1zPjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNzaGEyNTYiPjwvZHM6RGlnZXN0TWV0aG9kPjxkczpEaWdlc3RWYWx1ZT5PcGdxaG1pQTMyaDI5SVM4YzYrL2d6cHlyc2dmRzN6cHFkZkJTTjR2N0ZzPTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PGRzOlJlZmVyZW5jZSBVUkk9ImNpZDpkYWRlZGZmYy03N2RlLTQ0NjEtYWU1ZS1jMTFjMDZiMWY5NjRAbG9jYWxob3N0Ij48ZHM6VHJhbnNmb3Jtcz48ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL2RvY3Mub2FzaXMtb3Blbi5vcmcvd3NzL29hc2lzLXdzcy1Td0FQcm9maWxlLTEuMSNBdHRhY2htZW50LUNvbnRlbnQtU2lnbmF0dXJlLVRyYW5zZm9ybSI+PC9kczpUcmFuc2Zvcm0+PC9kczpUcmFuc2Zvcm1zPjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNzaGEyNTYiPjwvZHM6RGlnZXN0TWV0aG9kPjxkczpEaWdlc3RWYWx1ZT56eHptdXAxeDdpQzFlUFdNNDh0STZMcnhacnVsWGdzVEZockUrMlVIQ2xBPTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PC9kczpTaWduZWRJbmZvPg== 
2020-02-14 12:36:16,366  DEBUG [org.apache.cxf.ws.security.wss4j.policyhandlers.AbstractCommonBindingHandler] Asserting {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}RecipientToken 
2020-02-14 12:36:16,366  DEBUG [org.apache.cxf.ws.security.wss4j.policyhandlers.AbstractCommonBindingHandler] Asserting {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token 
2020-02-14 12:36:16,375  DEBUG [org.apache.xml.security.algorithms.JCEMapper] Request for URI http://www.w3.org/2009/xmlenc11#aes128-gcm 
2020-02-14 12:36:16,404  DEBUG [org.apache.xml.security.algorithms.JCEMapper] Request for URI http://www.w3.org/2009/xmlenc11#rsa-oaep 
2020-02-14 12:36:16,404  DEBUG [org.apache.xml.security.algorithms.JCEMapper] Request for URI http://www.w3.org/2001/04/xmlenc#sha256 
2020-02-14 12:36:16,408  DEBUG [org.apache.wss4j.dom.message.WSSecEncryptedKey] cipher blksize: 0 
2020-02-14 12:36:16,418  DEBUG [org.apache.xml.security.algorithms.JCEMapper] Request for URI http://www.w3.org/2009/xmlenc11#aes128-gcm 
2020-02-14 12:36:16,429  DEBUG [org.apache.xml.security.encryption.XMLCipher] Have functional IdentityTransformer: false 
2020-02-14 12:36:16,430  DEBUG [org.apache.xml.security.encryption.XMLCipher] Getting XMLCipher with transformation 
2020-02-14 12:36:16,430  DEBUG [org.apache.xml.security.encryption.XMLCipher] Constructing XMLCipher... 
2020-02-14 12:36:16,436  DEBUG [org.apache.xml.security.algorithms.JCEMapper] Request for URI http://www.w3.org/2009/xmlenc11#aes128-gcm 
2020-02-14 12:36:16,436  DEBUG [org.apache.xml.security.encryption.XMLCipher] JCE Algorithm = AES/GCM/NoPadding 
2020-02-14 12:36:16,437  DEBUG [org.apache.xml.security.algorithms.JCEMapper] Request for URI http://www.w3.org/2009/xmlenc11#aes128-gcm 
2020-02-14 12:36:16,437  DEBUG [org.apache.xml.security.algorithms.JCEMapper] Request for URI http://www.w3.org/2009/xmlenc11#aes128-gcm 
2020-02-14 12:36:16,445  DEBUG [org.apache.xml.security.encryption.XMLCipherUtil] Saw AES-GCM block cipher, attempting to create GCMParameterSpec: http://www.w3.org/2009/xmlenc11#aes128-gcm 
2020-02-14 12:36:16,446  DEBUG [org.apache.xml.security.encryption.XMLCipherUtil] Successfully created GCMParameterSpec 
2020-02-14 12:36:16,450  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleMessage on interceptor org.apache.cxf.ws.policy.PolicyVerificationOutInterceptor@647907dd 
2020-02-14 12:36:16,451  DEBUG [org.apache.cxf.ws.policy.PolicyVerificationOutInterceptor] Verified policies for outbound message. 
2020-02-14 12:36:16,451  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleMessage on interceptor org.apache.cxf.binding.soap.interceptor.SoapOutInterceptor$SoapOutEndingInterceptor@64a86e9a 
2020-02-14 12:36:16,452  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleMessage on interceptor org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor@6f7550c5 
2020-02-14 12:36:16,460  DEBUG [org.apache.cxf.transport.http.Headers] Accept: */* 
2020-02-14 12:36:16,460  DEBUG [org.apache.cxf.transport.http.HTTPConduit] No Trust Decider for Conduit '{oxalis.difi.no/}port.http-conduit'. An affirmative Trust Decision is assumed. 
2020-02-14 12:38:23,699  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor@6f7550c5 
2020-02-14 12:38:23,699  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.binding.soap.interceptor.SoapOutInterceptor$SoapOutEndingInterceptor@64a86e9a 
2020-02-14 12:38:23,699  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.ws.policy.PolicyVerificationOutInterceptor@647907dd 
2020-02-14 12:38:23,699  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor$PolicyBasedWSS4JOutInterceptorInternal@d72e221 
2020-02-14 12:38:23,699  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.wsdl.interceptors.BareOutInterceptor@273778c4 
2020-02-14 12:38:23,699  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.binding.soap.interceptor.SoapOutInterceptor@34474db 
2020-02-14 12:38:23,699  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JOutInterceptor@16735b03 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor@685c047a 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.jaxws.interceptors.MessageModeOutInterceptor$MessageModeOutInterceptorInternal@2d8f4d2a 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.interceptor.StaxOutInterceptor@5c8bb7cb 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.ws.security.wss4j.PolicyBasedWSS4JStaxOutInterceptor@2d2f8ce2 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.interceptor.AttachmentOutInterceptor@3823a823 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.ext.logging.LoggingOutInterceptor@6472ade5 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.interceptor.MessageSenderInterceptor@7d8193e8 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.jaxws.interceptors.MessageModeOutInterceptor@4bd0d960 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.binding.soap.interceptor.SoapPreProtocolOutInterceptor@270aeb1 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.ws.security.policy.interceptors.SecurityVerificationOutInterceptor@3e873fc1 
2020-02-14 12:38:23,700  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.binding.soap.interceptor.SoapHeaderOutFilterInterceptor@db03027 
2020-02-14 12:38:23,701  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.jaxws.interceptors.WrapperClassOutInterceptor@41abe1b 
2020-02-14 12:38:23,701  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.jaxws.interceptors.SwAOutInterceptor@c6d1438 
2020-02-14 12:38:23,701  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.jaxws.interceptors.HolderOutInterceptor@49cc7c21 
2020-02-14 12:38:23,701  DEBUG [org.apache.cxf.phase.PhaseInterceptorChain] Invoking handleFault on interceptor org.apache.cxf.ws.policy.PolicyOutInterceptor@1e451456 
2020-02-14 12:38:23,706  WARN [org.apache.cxf.phase.PhaseInterceptorChain] Interceptor for {oxalis.difi.no/}outbound-service#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now 
org.apache.cxf.binding.soap.SoapFault: Connection timed out (Connection timed out)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:221)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)

**Comment by FrodeBjerkholt** [comment]
Duplicate
